### ISSUE TITLE
find some bugs or difference

### ISSUE THREAD

**Issue by JunQu** [ryota-murakami/react-typescript-todo-example-2019#47] opened 2019-11-12 15:20 UTC
hi, thank you for this project,it help me a a lot.I I'm a novice at react, when I try a todo ,so I found there.After some try, I found some problems。
may be bug:

- edit multiple at the same time

- edit todo and then delete its contents. The style will be a little strange after unfocused.

mabe different from TodoMVC:

- can add spaces as todo

- can't always autofocus when edit

they all reappear in your online demo.
many of the above languages come from translation. If my tone is not good, please forgive me.

**Comment by ryota-murakami** [comment] 2019-11-13 11:01
@JunQu Thanks your response!
I'm busy so I'll make certainly response later.

**Comment by ryota-murakami** [comment] 2019-11-15 07:22
@JunQu Thanks I clould conformed difference between original, so I'm wiling fix them all! 😀

>mabe different from TodoMVC:
>
>can add spaces as todo
>
>can't always autofocus when edit

However, I couldn't reproduce bellow 2 bugs.

>may be bug:
>
>edit multiple at the same time
>
>edit todo and then delete its contents. The style will be a little strange after >unfocused.

I if you can show me reproduce video, that's really helpful for me!
Welcoming whatever way Upload Youtube, comment with gif, recorded movie file at any file storage service etc.. 📹

**Comment by JunQu** [comment] 2019-11-18 16:33
sorry, i not clear enough. I recorded a gif to show .
> edit multiple at the same time
![editM](https://user-images.githubusercontent.com/39846309/69070380-016a3880-0a63-11ea-912f-8f5ffef6d7bd.gif)


and 
> edit todo and then delete its contents. The style will be a little strange after unfocused.
 It look same as add spaces as todo . It’s what I said repeated.When I add a  spaces as todo, the situation is the same.

Thank you for your improvement and appreciate your project.

**Comment by ryota-murakami** [comment] 2019-11-25 01:39
### Progress
- [ ] edit multiple at the same time
- [ ] edit todo and then delete its contents. The style will be a little strange after unfocused.
- [x] ~~can add spaces as todo https://github.com/ryota-murakami/react-typescript-todo-example-2019/pull/52~~
- [ ] can't always autofocus when edit

**Comment by ryota-murakami** [comment] 2019-12-01 12:07
@JunQu Hello, I've fixed above 3 bugs!
But I'cant reproduce *edit multiple at the same time* now, I tried blow though 😅

- enter tab key
- click next todo element with hold shift (I did same check to command, control keys )

Could you still reproduce right now?
If you can reproduce, please tell me how to manipulate key/mouse to reproduce.
If you didn't get reproduce, might be fixed by involved fix works of 3 fixed problems.

Thanks your great report! 😀

**Comment by JunQu** [comment] 2019-12-01 15:42
@ryota-murakami Aha, I'cant reproduce *edit multiple at the same time* too. In latest version, it may be repaired. 🎉🎉🎉
In older versions, it may be caused by *can't always autofocus when edit* ,  in my recorded  gif , none of them are focused. And you could  reproduce it before fixed *can't always autofocus when edit*, when you have more than three todos, double-click without editing each one, a few more clicks will reproduce.

but in latest version,  when you have more than two todos, double-click one todo to edit, then delete its all contents, and then double-click  the other todo, you may look some thing like *edit multiple at the same time* .😅

Thank you for your support, as a newbie I feel very involved

**Comment by ryota-murakami** [comment] 2019-12-01 18:46
@JunQu Thank you for response!

> but in latest version, when you have more than two todos, double-click one todo to edit, then delete its all contents, and then double-click the other todo, you may look some thing like edit multiple at the same time .😅

Oh shit 😭I can reproduce to do same things your report.
So I confirmed original todomvc behavior that removing empty todo if you do any click action when blank value input.

I adopt and implement the behavior at new commit, so multiple edit like buggy UI should fixed now 😀

**Comment by JunQu** [comment] 2019-12-02 04:59
@ryota-murakami  so fast fix, all seems is OK 😀
 thanks this work, pretty good project.
I'll share this good project to other who the same as  me a novice at react.
😉

**Comment by ryota-murakami** [comment] 2019-12-02 06:25
@all-contoributors add @JunQu for bug

**Comment by ryota-murakami** [comment] 2019-12-02 06:28
@all-contributors please add @JunQu for bug

**Comment by ryota-murakami** [comment] 2019-12-02 06:31
@JunQu I'm glad to hear that!
And added you README as a contributor!

Thank you so much 🤗

**Closed by ryota-murakami** 2019-12-02 06:31 UTC
Labels: bug
